### ISSUE TITLE
Remove path and max_concurrency from func.yaml generated with `fn init`

### ISSUE THREAD

**Issue by treeder** [iron-io/functions#424]
File created looks like this:

```yaml
name: treeder/guppy
version: 0.0.1
runtime: ruby
entrypoint: ruby func.rb
path: /guppy
max_concurrency: 1
```

path and max_concurrency aren't required.
